# Generated by Django 3.0.8 on 2022-02-12 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='user',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
